module.exports = {
  //
  BROWSE_CARTITEMS: "BROWSE_CARTITEMS",
  READ_CARTITEM: "READ_CARTITEM",
  EDIT_CARTITEM: "EDIT_CARTITEM",
  ADD_CARTITEM: "ADD_CARTITEM",
  DELETE_CARTITEM: "DELETE_CARTITEM",
  //
  BROWSE_CATEGORIES: "BROWSE_CATEGORIES",
  READ_CATEGORY: "READ_CATEGORY",
  EDIT_CATEGORY: "EDIT_CATEGORY",
  ADD_CATEGORY: "ADD_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",
  //
  BROWSE_CATEGORYPRODUCTS: "BROWSE_CATEGORYPRODUCTS",
  READ_CATEGORYPRODUCT: "READ_CATEGORYPRODUCT",
  EDIT_CATEGORYPRODUCT: "EDIT_CATEGORYPRODUCT",
  ADD_CATEGORYPRODUCT: "ADD_CATEGORYPRODUCT",
  DELETE_CATEGORYPRODUCT: "DELETE_CATEGORYPRODUCT",
  //
  BROWSE_ORDERITEMS: "BROWSE_ORDERITEMS",
  READ_ORDERITEM: "READ_ORDERITEM",
  EDIT_ORDERITEM: "EDIT_ORDERITEM",
  ADD_ORDERITEM: "ADD_ORDERITEM",
  DELETE_ORDERITEM: "DELETE_ORDERITEM",
  //
  BROWSE_ORDERS: "BROWSE_ORDERS",
  READ_ORDER: "READ_ORDER",
  EDIT_ORDER: "EDIT_ORDER",
  ADD_ORDER: "ADD_ORDER",
  DELETE_ORDER: "DELETE_ORDER",
  //
  BROWSE_PERMISSIONROLES: "BROWSE_PERMISSIONROLES",
  READ_PERMISSIONROLE: "READ_PERMISSIONROLE",
  EDIT_PERMISSIONROLE: "EDIT_PERMISSIONROLE",
  ADD_PERMISSIONROLE: "ADD_PERMISSIONROLE",
  DELETE_PERMISSIONROLE: "DELETE_PERMISSIONROLE",
  //
  BROWSE_PERMISSION: "BROWSE_PERMISSION",
  READ_PERMISSION: "READ_PERMISSION",
  EDIT_PERMISSION: "EDIT_PERMISSION",
  ADD_PERMISSION: "ADD_PERMISSION",
  DELETE_PERMISSION: "DELETE_PERMISSION",
  //
  BROWSE_ROLES: "BROWSE_ROLES",
  READ_ROLE: "READ_ROLE",
  EDIT_ROLE: "EDIT_ROLE",
  ADD_ROLE: "ADD_ROLE",
  DELETE_ROLE: "DELETE_ROLE",
  //
  BROWSE_PRODUCTS: "BROWSE_PRODUCTS",
  READ_PRODUCT: "READ_PRODUCT",
  EDIT_PRODUCT: "EDIT_PRODUCT",
  ADD_PRODUCT: "ADD_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  //
  BROWSE_TOKENS: "BROWSE_TOKENS",
  READ_TOKEN: "READ_TOKEN",
  EDIT_TOKEN: "EDIT_TOKEN",
  ADD_TOKEN: "ADD_TOKEN",
  DELETE_TOKEN: "DELETE_TOKEN",
  //
  BROWSE_USERS: "BROWSE_USERS",
  READ_USER: "READ_USER",
  EDIT_USER: "EDIT_USER",
  ADD_USER: "ADD_USER",
  DELETE_USER: "DELETE_USER",
};
